print("this is added in master")
print("again added")
print("Day 1 - Python Print Function")
print("The function is declared like this:")
print("print('what to print')")
print("changes in branch")
print("This piece of code is updated in remote repository")
print("this too updated in remote repo")
